# Generated by Django 4.2.4 on 2023-08-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
                ('pic_email', models.EmailField(max_length=25)),
                ('slug', models.CharField(max_length=25)),
                ('project', models.CharField(choices=[('Moladin Finance Indonesia', 'MFI'), ('Moladin Digital Indonesia', 'MDI')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tech_family',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('backend', 'BE'), ('frontend', 'FE')], max_length=10)),
                ('project', models.CharField(choices=[('Moladin Finance Indonesia', 'MFI'), ('Moladin Digital Indonesia', 'MDI')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techfamily')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=12)),
                ('date', models.DateField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.service')),
            ],
            options={
                'db_table': 'metric',
            },
        ),
        migrations.CreateModel(
            name='IndexWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techfamily')),
            ],
            options={
                'db_table': 'index_weight',
            },
        ),
    ]
