# Generated by Django 4.2.4 on 2023-08-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
                ('pic_email', models.EmailField(max_length=25)),
                ('slug', models.CharField(max_length=25)),
                ('project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tech_family',
            },
        ),
        migrations.CreateModel(
            name='IndexWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techfamily')),
            ],
            options={
                'db_table': 'index_weight',
            },
        ),
    ]
