# Generated by Django 4.2.4 on 2023-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='project',
            field=models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='techfamily',
            name='project',
            field=models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=30),
        ),
    ]
