# Generated by Django 4.2.4 on 2023-08-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_techfamily_project_service_metric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metric',
            table='metric',
        ),
    ]
