# Generated by Django 4.2.4 on 2023-08-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_service_project_alter_techfamily_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubecostClusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gcp_project', models.CharField(max_length=100)),
                ('company_project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=100)),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'kubecost_clusters',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='tech_family',
        ),
        migrations.AlterField(
            model_name='indexweight',
            name='tech_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_weight', to='home.techfamily'),
        ),
        migrations.AlterModelTable(
            name='metric',
            table='metrics',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('backend', 'BE'), ('frontend', 'FE'), ('infra', 'INFRA')], max_length=10)),
                ('project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techfamily')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='KubecostNamespacesMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.services')),
            ],
            options={
                'db_table': 'kubecost_namespace_map',
            },
        ),
        migrations.CreateModel(
            name='KubecostNamespaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=12)),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=12)),
                ('cpu_cost', models.FloatField()),
                ('memory_cost', models.FloatField()),
                ('pv_cost', models.FloatField()),
                ('lb_cost', models.FloatField()),
                ('network_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.kubecostclusters')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.services')),
            ],
            options={
                'db_table': 'kubecost_namespaces',
            },
        ),
        migrations.CreateModel(
            name='KubecostDeployments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment', models.CharField(max_length=100, null=True)),
                ('namespace', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=12)),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=12)),
                ('cpu_cost', models.FloatField()),
                ('memory_cost', models.FloatField()),
                ('pv_cost', models.FloatField()),
                ('lb_cost', models.FloatField()),
                ('network_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.kubecostclusters')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.services')),
            ],
            options={
                'db_table': 'kubecost_deployments',
            },
        ),
        migrations.AddConstraint(
            model_name='kubecostclusters',
            constraint=models.UniqueConstraint(fields=('cluster_name', 'gcp_project'), name='unique_cluster_name_gcp_project'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.services'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddConstraint(
            model_name='services',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_name_project'),
        ),
        migrations.AddConstraint(
            model_name='kubecostnamespacesmap',
            constraint=models.UniqueConstraint(fields=('namespace', 'project'), name='unique_namespace_project'),
        ),
        migrations.AddConstraint(
            model_name='kubecostnamespaces',
            constraint=models.UniqueConstraint(fields=('namespace', 'cluster', 'date'), name='unique_namespace_cluster_date'),
        ),
        migrations.AddConstraint(
            model_name='kubecostdeployments',
            constraint=models.UniqueConstraint(fields=('deployment', 'namespace', 'cluster', 'date'), name='unique_deployment_namespace_cluster_date'),
        ),
    ]
