# Generated by Django 4.2.4 on 2023-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_kubecostclusters_remove_service_tech_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfamily',
            name='pic_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='techfamily',
            name='project',
            field=models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='techfamily',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
